# Generated by Django 4.1.7 on 2023-03-22 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=32)),
                ('job_title', models.CharField(blank=True, default='', max_length=200)),
                ('section', models.CharField(blank=True, default='', max_length=200)),
                ('id_no', models.CharField(blank=True, default='', max_length=32)),
                ('nin', models.CharField(blank=True, default='', max_length=32)),
                ('date_joined', models.DateField(blank=True)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=32)),
                ('birth_place', models.CharField(blank=True, default='', max_length=200)),
                ('residence', models.CharField(blank=True, default='', max_length=200)),
                ('birth_date', models.DateField(blank=True)),
                ('kin_name', models.CharField(blank=True, default='', max_length=200)),
                ('kin_contact', models.CharField(blank=True, default='', max_length=200)),
                ('emergency_contact', models.CharField(blank=True, default='', max_length=200)),
                ('comment', models.TextField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_employees', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_employees', to='org.department')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], max_length=32)),
                ('approved', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_employee_requests', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('filename', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('category', models.CharField(choices=[('Personal', 'Personal'), ('Education', 'Education'), ('HR', 'HR')], max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_employee_documents', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_documents', to='people.employee')),
            ],
        ),
    ]
